version: 2
jobs:
  build_node_image:
    machine:
      enabled: true
      resource_class: mayurwaghmode/runner
    steps:
      - run: arch
      - run:
          name: SSH into the power machine
          command: |
            git clone -b ssh-power https://github.com/mayurwaghmode/kind-images.git
            sshpass -p Changepassword@123 ssh root@9.30.248.38 < ./root/kind-images/rm.sh

workflows:
  version: 2
  build_images:
    jobs:
      - build_node_image
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_node_image
