version: 2
jobs:
  build_node_image:
    machine:
      enabled: true
      resource_class: mayurwaghmode/alkalify1-x86-runner
    steps:
      - run: arch
      - run:
          name: Fix ssh Could not resolve hostname
          command: |
            ssh-keyscan 9.30.140.113 >> ~/.ssh/known_hosts # Add live server IP to known hosts.
      - add_ssh_keys: # add private SSH key from CircleCI account based on fingerprint.
          fingerprints:
            - "SHA256:5L/0DVwFUNmuF1JjWIyJfvekdIw5wV+zO3R61wAMj4w"
      - run:
          name: Build and test node image on ppc64le architecture
          command: |
            echo $QUAY_REPO:$(uname -m)
            echo "$QUAY_PASS"
            sudo rm -rf /root/$GH_REPO
            git clone -b hosted-multi-arch https://github.com/mayurwaghmode/circleCI-multi-arch.git /root/$GH_REPO
            cd /root/$GH_REPO
            chmod +x /root/$GH_REPO/build-on-ppc64le.sh
            echo -e "SSH into the ppc64le machine and execute the script\n"
            ssh root@9.30.140.113 < /root/$GH_REPO/build-on-ppc64le.sh $GH_REPO "$QUAY_REPO" "$QUAY_USER" "$QUAY_PASS"
            
workflows:
  version: 2
  build_images:
    jobs:
      - build_node_image
