version: 2
jobs:
  build_node_image:
    machine:
      enabled: true
      resource_class: mayurwaghmode/kind-runner-x86
    steps:
      - run: arch
      - run:
          name: Fix ssh Could not resolve hostname
          command: |
            ssh-keyscan 169.54.110.122 >> ~/.ssh/known_hosts # Add live server IP to known hosts.
      - add_ssh_keys: # add private SSH key from CircleCI account based on fingerprint.
          fingerprints:
            - "SHA256:H4oJmU8SvvL87bsViII/1U369zx4wwZoXhyixaduktk"
      - run:
          name: Build and test node image on ppc64le architecture
          command: |
            rm -rf /root/kind-images
            git clone -b ssh-power https://github.com/mayurwaghmode/kind-images.git /root/kind-images
            echo -e "SSH into the Power machine and execute the script\n"
            ssh root@169.54.110.122 < /root/kind-images/test-node-image.sh

workflows:
  version: 2
  build_images:
    jobs:
      - build_node_image
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_node_image
