version: 2
jobs:
  build_node_image:
    machine:
      enabled: true
      image: ubuntu-2004:202101-01
    working_directory: ~/.go_workspace/src/sigs.k8s.io/kind
    steps:
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: git clone https://github.com/kubernetes-sigs/kind.git .
      - run: GOOS=linux GOARCH=ppc64le make build
      - run: ./bin/kind version
    
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/ppc64le/kubectl
            chmod +x kubectl
            sudo cp kubectl /usr/local/bin/
      
      - run:
          name: Create kind cluster
          command: |
            KUBECONFIG="${HOME}/kind-test-config"
            export KUBECONFIG
            ./bin/kind create cluster --image quay.io/mayurwaghmode111/node-ppc64le:ppc64le -v=3 --wait 1m --retain
            kubectl get nodes -o wide
            kubectl get pods --all-namespaces -o wide
            kubectl get services --all-namespaces -o wide
     

workflows:
  version: 2
  build_images:
    jobs:
      - build_node_image
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_node_image
