version: 2
jobs:
  build_node_image:
    machine:
      enabled: true
      resource_class: mayurwaghmode/runner
    steps:
      - run:
          name: SSH into the power machine
          command: |
            sshpass -p Changepassword@123 ssh root@9.30.248.38
            pwd
            ls

      - run:
          name: Create kind cluster
          command: |
            KUBECONFIG="${HOME}/kind-test-config"
            export KUBECONFIG
            kind create cluster --image quay.io/mayurwaghmode111/node-ppc64le:ppc64le -v=3 --wait 1m --retain
            kubectl get nodes -o wide
            kubectl get pods --all-namespaces -o wide
            kubectl get services --all-namespaces -o wide
      - run:
          command: |
            mkdir -p /tmp/kind
            kind export logs /tmp/kind
          when: on_fail
      - store_artifacts:
          path: /tmp/kind

workflows:
  version: 2
  build_images:
    jobs:
      - build_node_image
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_node_image
